question1:
	python dataClassifier.py -c perceptron

question2:
	python dataClassifier.py -c perceptron -w

question3:
	python dataClassifier.py -c mira --autotune

question4:
	python dataClassifier.py -d digits -c naiveBayes -f -a -t 1000

question5:
	python dataClassifier.py -c perceptron -d pacman

question6:
	python dataClassifier.py -c perceptron -d pacman -f -g ContestAgent -t 1000 -s 1000
