question1:
	python autograder.py -q q1

question2-exmaple: 
	python autograder.py -t test_cases/q2/2-ExactElapse

question2:
	python autograder.py -q q2 --no-graphics

question3:
	python autograder.py -q q3 --no-graphics

question4:
	python autograder.py -q q4 --no-graphics


question5:
	python autograder.py -q q5 --no-graphics

question5-exmaple:
  python autograder.py -t test_cases/q5/2-ParticleElapse

question6:
	python autograder.py -q q6 --no-graphics

question7:
	python autograder.py -q q7 --no-graphics
