test1:
	python pacman.py -p ReflexAgent -l testClassic
	python pacman.py --frameTime 0 -p ReflexAgent -k 1
	python pacman.py --frameTime 0 -p ReflexAgent -k 2

test2:
# python autograder.py -q q2
	python autograder.py -q q2 --no-graphics

test3:
	# python pacman.py -p AlphaBetaAgent -a depth=3 -l smallClassic
# python autograder.py -q q3
	python autograder.py -q q3 --no-graphics

test4:
	python pacman.py -p ExpectimaxAgent -l minimaxClassic -a depth=3
	python pacman.py -p AlphaBetaAgent -l trappedClassic -a depth=3 -q -n 10
	python pacman.py -p ExpectimaxAgent -l trappedClassic -a depth=3 -q -n 10

test5:
	python autograder.py -q q5 --no-graphics

